cleaning zsh

diff --git a/zsh/.zsh.d/prompt b/zsh/.zsh.d/prompt
--- a/zsh/.zsh.d/prompt
+++ b/zsh/.zsh.d/prompt
@@ -1,76 +1,241 @@
-#!/usr/bin/env zsh
+# Global settings
+MNML_OK_COLOR="${MNML_OK_COLOR:-2}"
+MNML_ERR_COLOR="${MNML_ERR_COLOR:-1}"
+MNML_WHITE_COLOR="${MNML_WHITE_COLOR:-7}"
 
-autoload -U colors && colors
+MNML_USER_CHAR="${MNML_USER_CHAR:-λ}"
+MNML_INSERT_CHAR="${MNML_INSERT_CHAR:-›}"
+MNML_NORMAL_CHAR="${MNML_NORMAL_CHAR:-·}"
 
-setopt prompt_subst
+[ -z "$MNML_PROMPT" ] && MNML_PROMPT=(mnml_ssh mnml_pyenv mnml_status mnml_keymap)
+[ -z "$MNML_RPROMPT" ] && MNML_RPROMPT=('mnml_cwd 2 0' mnml_git)
+[ -z "$MNML_INFOLN" ] && MNML_INFOLN=(mnml_err mnml_jobs mnml_uhp mnml_files)
 
-function git_branch_name() {
-  local branch_name="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)"
-  [[ -n $branch_name ]] && echo "$branch_name"
+[ -z "$MNML_MAGICENTER" ] && MNML_MAGICENTER=(mnml_me_dirs mnml_me_ls mnml_me_git)
+
+# Components
+function mnml_status {
+    local okc="$MNML_OK_COLOR"
+    local errc="$MNML_ERR_COLOR"
+    local uchar="$MNML_USER_CHAR"
+
+    local job_ansi="0"
+    if [ -n "$(jobs | sed -n '$=')" ]; then
+        job_ansi="4"
+    fi
+
+    local err_ansi="$MNML_OK_COLOR"
+    if [ "$MNML_LAST_ERR" != "0" ]; then
+        err_ansi="$MNML_ERR_COLOR"
+    fi
+
+    echo -n "%{\e[$job_ansi;3${err_ansi}m%}%(!.#.$uchar)%{\e[0m%}"
 }
 
-function git_repo_status(){
-  local rs="$(git status --porcelain)"
-
-  if $(echo "$rs" | grep -v '^##' &> /dev/null); then # is dirty
-    echo "%{$fg[red]%}"
-  elif $(echo "$rs" | grep '^## .*diverged' &> /dev/null); then # has diverged
-    echo "%{$fg[red]%}"
-  elif $(echo "$rs" | grep '^## .*behind' &> /dev/null); then # is behind
-    echo "%{[38;5;011m%}%}"
-  elif $(echo "$rs" | grep '^## .*ahead' &> /dev/null); then # is ahead
-    echo "%{$fg[white]%}"
-#    echo "%{$reset_color%}"
-  else # is clean
-    echo "%{$fg[green]%}"
-  fi
+function mnml_keymap {
+    local kmstat="$MNML_INSERT_CHAR"
+    [ "$KEYMAP" = 'vicmd' ] && kmstat="$MNML_NORMAL_CHAR"
+    echo -n "$kmstat"
 }
 
-function prompt_git() {
-  local bname=$(git_branch_name)
-  if [[ -n $bname ]]; then
-    local infos="$(git_repo_status)$bname%{$reset_color%}"
-    echo " $infos"
-  fi
+function mnml_cwd {
+    local segments="${1:-2}"
+    local seg_len="${2:-0}"
+
+    local _w="%{\e[0m%}"
+    local _g="%{\e[38;5;244m%}"
+
+    if [ "$segments" -le 0 ]; then
+        segments=1
+    fi
+    if [ "$seg_len" -gt 0 ] && [ "$seg_len" -lt 4 ]; then
+        seg_len=4
+    fi
+    local seg_hlen=$((seg_len / 2 - 1))
+
+    local cwd="%${segments}~"
+    cwd="${(%)cwd}"
+    cwd=("${(@s:/:)cwd}")
+
+    local pi=""
+    for i in {1..${#cwd}}; do
+        pi="$cwd[$i]"
+        if [ "$seg_len" -gt 0 ] && [ "${#pi}" -gt "$seg_len" ]; then
+            cwd[$i]="${pi:0:$seg_hlen}$_w..$_g${pi: -$seg_hlen}"
+        fi
+    done
+
+    echo -n "$_g${(j:/:)cwd//\//$_w/$_g}$_w"
 }
 
-function prompt_hostname(){
-    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
-        echo "%{\033[0;34m%}$(hostname -s) %{\033[m%}"
+function mnml_git {
+    local statc="%{\e[0;3${MNML_OK_COLOR}m%}" # assume clean
+    local bname="$(git rev-parse --abbrev-ref HEAD 2> /dev/null)"
+
+    if [ -n "$bname" ]; then
+        local rs="$(git status --porcelain -b)"
+        if $(echo "$rs" | grep -v '^##' &> /dev/null); then # is dirty
+            statc="%{\e[0;3${MNML_ERR_COLOR}m%}"
+        elif $(echo "$rs" | grep '^## .*diverged' &> /dev/null); then # has diverged
+            statc="%{\e[0;3${MNML_ERR_COLOR}m%}"
+        elif $(echo "$rs" | grep '^## .*behind' &> /dev/null); then # is behind
+            statc="%{\e[0;3${MNML_WHITE_COLOR}m%}"
+        elif $(echo "$rs" | grep '^## .*ahead' &> /dev/null); then # is ahead
+            statc="%{\e[0;3${MNML_WHITE_COLOR}m%}"
+        else # is clean
+            statc="%{\e[0;3${MNML_OK_COLOR}m%}"
+        fi
+
+        echo -n "$statc$bname%{\e[0m%}"
     fi
 }
 
+function mnml_uhp {
+    local _w="%{\e[0m%}"
+    local _g="%{\e[38;5;244m%}"
+    local cwd="%~"
+    cwd="${(%)cwd}"
 
-function zle-line-init zle-line-finish zle-keymap-select {
-  zle reset-prompt
-  zle -R
+    echo -n "$_g%n$_w@$_g%m$_w:$_g${cwd//\//$_w/$_g}$_w"
 }
 
-zle -N zle-line-init
-zle -N zle-keymap-select
-zle -N zle-line-finish
+function mnml_ssh {
+    if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
+        echo -n "$(hostname -s)"
+    fi
+}
 
-PROMPT='$(
-[ $? -eq 0 ] && color=2 || color=1
+function mnml_pyenv {
+    if [ -n "$VIRTUAL_ENV" ]; then
+        _venv="$(basename $VIRTUAL_ENV)"
+        echo -n "${_venv%%.*}"
+    fi
+}
 
-printf "\n"
-echo -e "%{\033[1;3${color}m│\033[m%} $(prompt_hostname)%~$(prompt_git)"
-echo -e "%2{\033[1;3${color}m│\033[m %}"
-)'
-RPROMPT=''
+function mnml_err {
+    local _w="%{\e[0m%}"
+    local _err="%{\e[3${MNML_ERR_COLOR}m%}"
 
-SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '
+    if [ "${MNML_LAST_ERR:-0}" != "0" ]; then
+        echo -n "$_err$MNML_LAST_ERR$_w"
+    fi
+}
 
-###
-# for man pages in color
-###
-export LESS_TERMCAP_mb=$'\e[0;33m'
-export LESS_TERMCAP_md=$'\e[0;34m'
-export LESS_TERMCAP_me=$'\e[0m'
-export LESS_TERMCAP_se=$'\e[0m'
-export LESS_TERMCAP_so=$'\e[1;34;30m'
-export LESS_TERMCAP_ue=$'\e[0m'
-export LESS_TERMCAP_us=$'\e[0;31m'
+function mnml_jobs {
+    local _w="%{\e[0m%}"
+    local _g="%{\e[38;5;244m%}"
 
-export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
+    local job_n="$(jobs | sed -n '$=')"
+    if [ "$job_n" -gt 0 ]; then
+        echo -n "$_g$job_n$_w&"
+    fi
+}
 
+function mnml_files {
+    local _w="%{\e[0m%}"
+    local _g="%{\e[38;5;244m%}"
+
+    local a_files="$(ls -1A | sed -n '$=')"
+    local v_files="$(ls -1 | sed -n '$=')"
+    local h_files="$((a_files - v_files))"
+
+    local output="${_w}[$_g${v_files:-0}"
+    if [ "${h_files:-0}" -gt 0 ]; then
+        output="$output $_w($_g$h_files$_w)"
+    fi
+    output="$output${_w}]"
+
+    echo -n "$output"
+}
+
+# Magic enter functions
+function mnml_me_dirs {
+    local _w="\e[0m"
+    local _g="\e[38;5;244m"
+
+    if [ "$(dirs -p | sed -n '$=')" -gt 1 ]; then
+        local stack="$(dirs)"
+        echo "$_g${stack//\//$_w/$_g}$_w"
+    fi
+}
+
+function mnml_me_ls {
+    if [ "$(uname)" = "Darwin" ] && ! /usr/bin/ls --version &> /dev/null; then
+        COLUMNS=$COLUMNS CLICOLOR_FORCE=1 /usr/bin/ls -C -G -F
+    else
+        /usr/bin/ls -C -F --color="always" -w $COLUMNS
+    fi
+}
+
+function mnml_me_git {
+    git -c color.status=always status -sb 2> /dev/null
+}
+
+# Wrappers & utils
+# join outpus of components
+function mnml_wrap {
+    local arr=()
+    local cmd_out=""
+    for cmd in ${(P)1}; do
+        cmd_out="$(eval "$cmd")"
+        if [ -n "$cmd_out" ]; then
+            arr+="$cmd_out"
+        fi
+    done
+
+    echo -n "${(j: :)arr}"
+}
+
+# expand string as prompt would do
+function mnml_iline {
+    echo "${(%)1}"
+}
+
+# display magic enter
+function mnml_me {
+    local output=()
+    local cmd_output=""
+    for cmd in $MNML_MAGICENTER; do
+        cmd_out="$(eval "$cmd")"
+        if [ -n "$cmd_out" ]; then
+            output+="$cmd_out"
+        fi
+    done
+    echo -n "${(j:\n:)output}" | less -XFR
+}
+
+# capture exit status and reset prompt
+function mnml_line_init {
+    MNML_LAST_ERR="$?" # I need to capture this ASAP
+    zle reset-prompt
+}
+
+# redraw prompt on keymap select
+function mnml_keymap_select {
+    zle reset-prompt
+}
+
+# draw infoline if no command is given
+function mnml_buffer_empty {
+    if [ -z "$BUFFER" ]; then
+        mnml_iline "$(mnml_wrap MNML_INFOLN)"
+        mnml_me
+        zle redisplay
+    else
+        zle accept-line
+    fi
+}
+
+# Setup
+autoload -U colors && colors
+setopt prompt_subst
+
+PROMPT='$(mnml_wrap MNML_PROMPT) '
+RPROMPT='$(mnml_wrap MNML_RPROMPT)'
+
+zle -N zle-line-init mnml_line_init
+zle -N zle-keymap-select mnml_keymap_select
+zle -N buffer-empty mnml_buffer_empty
+
+bindkey -M main  "^M" buffer-empty
+bindkey -M vicmd "^M" buffer-empty
